---
server:
  port: 8080
  contextPath: /hsservice
---
spring:
  profiles: prod,default
datasource:
    url: jdbc:mysql://localhost:3306/hsdata
    dbusername: root
    dbpassword: qazwsx123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
socket:
  socketaddress: 127.0.0.1
  socketport: 9090
  heartbeatinternal: 3000000
  sweepbeatinternal: 5000