#spring
spring:
  profiles:
    active: prod
  main:
    banner-mode: off
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/hsdata?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: hsbackend
    password: GB5vesBts
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  contextPath: /hsservice

security:
  user:
    name: admin
#    password: 123456

#actuator
management:
  security:
    enabled: true
    roles: admin
  port: 8084
  context-path: /hsservice/monitor #actuator的访问路径
endpoints:
  enabled: false
#  beans:
#    enabled: true
#  health:
#    enabled: true
#  dump:
#    enabled: true
#  metrics:
#    enabled: true
#  autoconfig:
#    enabled: true
#  configprops:
#    enabled: true
#  env:
#    enabled: true
#info:
#   app:
#      name: spring-boot-actuator
#      version: 1.0.0
socket:
  socketport: 8090
  socketport4g: 8089
  heartbeatinternal: 120000
  sweepbeatinternal: 10000
influxDB:
  username: hsuser
  password: qazwssx123
  url: http://localhost:8086
  retentionpolicy: autogen
  name: metrics
  batchtimeout: 1000
  batchsize: 1000
msg:
  processMsgThreadNum: 20
  responseDelay: 3000
order:
  interval:
     flag: false
     min: 2
     max: 10
# JWT
jwt:
  header: Authorization
  secret: knocknock
  expiration: 86400
  tokenHead: "Bearer "
  route:
    authentication:
      login: "login"
      userinfo: "userinfo"
      refresh: "refresh"
      register: "auth/register"

---
spring:
  profiles: dev
socket:
  socketaddress: localhost
---
spring:
  profiles: prod
socket:
  socketaddress: 172.16.74.156