---
server:
  port: 8080
  contextPath: /hsservice
---
datasource:
    databaseurl: jdbc:mysql://localhost:3306/
    dbusername: hsbackend
    dbpassword: GB5vesBts
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    databaseName: hsdata
socket:
  socketaddress: localhost
  socketport: 8090
  socketport4g: 8089
  heartbeatinternal: 10000
  sweepbeatinternal: 1000
influxDB:
  username: hsuser
  password: qazwssx123
  url: http://localhost:8086
  retentionpolicy: autogen
  name: metrics
  batchtimeout: 1000
  batchsize: 1000
msg:
  processMsgThreadNum: 20
  responseDelay: 1000
order:
  interval:
     flag: false
     min: 2
     max: 10
