---
server:
  port: 8080
  contextPath: /hsservice
---
datasource:
    databaseurl: jdbc:mysql://localhost:3306/
    dbusername: root
    dbpassword: qazwsx123
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 50
    databaseName: hsdata
socket:
  socketaddress: 172.16.74.156
  socketport: 8090
  socketport4g: 8089
  heartbeatinternal: 120000
  sweepbeatinternal: 10000
influxDB:
  username: hsuser
  password: qazwsx123
  url: http://localhost:8086
  retentionpolicy: autogen
  name: metrics
  batchtimeout: 1000
  batchsize: 1000
msg:
  processMsgThreadNum: 20
  responseDelay: 3000
order:
  interval:
     flag: false
     min: 2
     max: 5
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
  tokenHead: "Bearer "
  route:
    authentication:
      login: "login"
      userinfo: "userinfo"
      refresh: "refresh"
      register: "auth/register"