---
server:
  port: 8080
  contextPath: /hsservice
---
datasource:
    databaseurl: jdbc:mysql://localhost:3306/
    dbusername: hsbackend
    dbpassword: GB5vesBts
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    databaseName: hsdata
socket:
  socketaddress: localhost
  socketport: 8090
  heartbeatinternal: 180000
  sweepbeatinternal: 10000
influxDB:
  username: hsuser
  password: qazwsx123
  url: http://localhost:8086
  retentionpolicy: default
  name: metrics
  batchtimeout: 1000
  batchsize: 1000
msg:
  processMsgThreadNum: 20
  responseDelay: 3000
