---
server:
  port: 8080
  contextPath: /hsservice
---
datasource:
    databaseurl: jdbc:mysql://localhost:3306/
    dbusername: hsbackend
    dbpassword: GB5vesBts
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    databaseName: hsdata
socket:
  socketaddress: 172.16.74.156
  socketport: 8090
  heartbeatinternal: 300000
  sweepbeatinternal: 30000
influxDB:
  username: hsuser
  password: qazwsx123
  url: http://localhost:8086
  retentionpolicy: default
  name: metrics
  batchtimeout: 1000
  batchsize: 1000
msg:
  processMsgThreadNum: 20
  responseDelay: 3000
order:
  interval:
     flag: false
     min: 2
     max: 5